services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "ERPNet_Dev123!"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  rabbitmq:
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: "erpnet"
      RABBITMQ_DEFAULT_PASS: "ERPNet_Dev123!"
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "erpnet"
      MINIO_ROOT_PASSWORD: "ERPNet_Dev123!"
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Consola web
    volumes:
      - minio-data:/data

volumes:
  sqlserver-data:
  rabbitmq-data:
  minio-data:
